"""Orchestrator do CHARUTEI: Router, Registry, Governance e cascata de inteligência."""

from charutei_orchestrator.agent_loop import (
    AgentRunResult,
    AgentTool,
    AnthropicToolRunner,
    FakeToolRunner,
    ToolCallTrace,
    ToolResult,
    ToolRunner,
    build_tool_runner,
)
from charutei_orchestrator.cascade import (
    Cascade,
    DeterministicResolver,
    GenerationOutput,
    Generator,
    KgVersionFn,
)
from charutei_orchestrator.governance import EscalationDecision, Governance, GovernanceError
from charutei_orchestrator.mcp_tools import (
    CigarTools,
    DocRetriever,
    RetrievedDoc,
    build_cigar_tools,
    build_mcp_server,
)
from charutei_orchestrator.metrics import CascadeMetrics, cascade_metrics
from charutei_orchestrator.providers import (
    EmbeddingProvider,
    FakeEmbeddingProvider,
    FakeImageEmbeddingProvider,
    FakeLLMProvider,
    FakeOCRProvider,
    FakeTracer,
    FakeVisionProvider,
    ImageEmbeddingProvider,
    LLMProvider,
    LLMResponse,
    OCRProvider,
    Tracer,
    TraceRecord,
    VisionProvider,
    VisionResult,
    build_band_providers,
    build_providers,
    build_tracer,
    llm_cost,
    vision_cost,
)
from charutei_orchestrator.registry import TIER_MODELS, AgentRegistry, AgentSpec
from charutei_orchestrator.router import Intent, RouteDecision, classify
from charutei_orchestrator.supervisor import AgentHandler, RequestKind, Supervisor

__all__ = [
    "Cascade",
    "DeterministicResolver",
    "GenerationOutput",
    "Generator",
    "KgVersionFn",
    "CascadeMetrics",
    "cascade_metrics",
    "Governance",
    "GovernanceError",
    "EscalationDecision",
    "AgentRegistry",
    "AgentSpec",
    "TIER_MODELS",
    "classify",
    "Intent",
    "RouteDecision",
    "LLMProvider",
    "EmbeddingProvider",
    "Tracer",
    "TraceRecord",
    "LLMResponse",
    "FakeLLMProvider",
    "FakeEmbeddingProvider",
    "FakeTracer",
    "build_providers",
    "llm_cost",
    "ImageEmbeddingProvider",
    "OCRProvider",
    "VisionProvider",
    "VisionResult",
    "FakeImageEmbeddingProvider",
    "FakeOCRProvider",
    "FakeVisionProvider",
    "build_band_providers",
    "build_tracer",
    "vision_cost",
    "AgentTool",
    "AgentRunResult",
    "ToolCallTrace",
    "ToolResult",
    "ToolRunner",
    "FakeToolRunner",
    "AnthropicToolRunner",
    "build_tool_runner",
    "CigarTools",
    "DocRetriever",
    "RetrievedDoc",
    "build_cigar_tools",
    "build_mcp_server",
    "Supervisor",
    "RequestKind",
    "AgentHandler",
]
